export const BASE_URL = 'http://localhost:8080/api'
export const URL_WEB_SOCKET = 'http://localhost:8080'
export const URL_CHAT_AI = 'http://localhost:8080'
// export const BASE_URL = 'https://pike-armor-ms-hampton.trycloudflare.com/api'
// export const URL_WEB_SOCKET = 'https://pike-armor-ms-hampton.trycloudflare.com'
// export const URL_CHAT_AI = 'https://pike-armor-ms-hampton.trycloudflare.com'
