name: Build and Test

on:
  pull_request:
    branches:
      - '**'
    paths: # Chỉ chạy workflow khi có thay đổi trong các đường dẫn sau
      - 'HomeCleanAPI/**' # Bao gồm tất cả các file và thư mục con trong HomeCleanAPI
      - '.github/workflows/build.yml' # Để workflow tự cập nhật khi thay đổi file này (tùy chọn)

# Hoặc sử dụng paths-ignore nếu bạn muốn loại trừ một số đường dẫn con trong HomeCleanAPI
#    paths-ignore:
#      - 'HomeCleanAPI/test/**' # Ví dụ: bỏ qua thư mục test

jobs:
  build:
    name: Build and Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Run Tests
        run: mvn test --no-transfer-progress