--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-04-29 15:24:01

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 28281)
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- TOC entry 6150 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


--
-- TOC entry 1722 (class 1247 OID 18868)
-- Name: service_type_enum; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.service_type_enum AS ENUM (
    'Basic',
    'On-demand'
);


ALTER TYPE public.service_type_enum OWNER TO postgres;

--
-- TOC entry 813 (class 1255 OID 36616)
-- Name: update_cleaner_feedback_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.update_cleaner_feedback_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  -- Chỉ cập nhật 'updated_at' nếu rating hoặc comment thay đổi
  IF (NEW.rating <> OLD.rating OR NEW.comment <> OLD.comment) THEN
    NEW.updated_at = CURRENT_TIMESTAMP;  -- Cập nhật 'updated_at' nếu có sự thay đổi
  ELSE
    NEW.updated_at = OLD.updated_at;  -- Giữ nguyên 'updated_at' nếu không có thay đổi
  END IF;
  RETURN NEW;
END;
$$;


ALTER FUNCTION public.update_cleaner_feedback_updated_at() OWNER TO postgres;

--
-- TOC entry 555 (class 1255 OID 36534)
-- Name: update_feedback_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.update_feedback_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.updated_at = NOW(); -- Cập nhật updated_at mỗi khi có thay đổi
  RETURN NEW; 
END;
$$;


ALTER FUNCTION public.update_feedback_updated_at() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 278 (class 1259 OID 36720)
-- Name: admin_transaction_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin_transaction_history (
    id bigint NOT NULL,
    amount double precision,
    description character varying(255),
    payment_method character varying(255),
    status character varying(255),
    transaction_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    transaction_type character varying(255),
    cleaner_id integer,
    customer_id integer
);


ALTER TABLE public.admin_transaction_history OWNER TO postgres;

--
-- TOC entry 277 (class 1259 OID 36719)
-- Name: admin_transaction_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admin_transaction_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_transaction_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 18801)
-- Name: administrators; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.administrators (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255),
    fullname character varying(255) NOT NULL,
    role_id bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.administrators OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 18800)
-- Name: administrators_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.administrators_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.administrators_id_seq OWNER TO postgres;

--
-- TOC entry 6151 (class 0 OID 0)
-- Dependencies: 224
-- Name: administrators_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.administrators_id_seq OWNED BY public.administrators.id;


--
-- TOC entry 229 (class 1259 OID 18837)
-- Name: cleaner_addresses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cleaner_addresses (
    id integer NOT NULL,
    cleaner_id integer,
    address character varying(255),
    latitude double precision,
    longitude double precision,
    is_current boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    geom public.geometry(Point,4326)
);


ALTER TABLE public.cleaner_addresses OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 18836)
-- Name: cleaner_addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.cleaner_addresses_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.cleaner_addresses_id_seq OWNER TO postgres;

--
-- TOC entry 6152 (class 0 OID 0)
-- Dependencies: 228
-- Name: cleaner_addresses_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.cleaner_addresses_id_seq OWNED BY public.cleaner_addresses.id;


--
-- TOC entry 266 (class 1259 OID 36588)
-- Name: cleaner_feedback; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cleaner_feedback (
    id bigint NOT NULL,
    job_id bigint NOT NULL,
    cleaner_id bigint NOT NULL,
    rating double precision,
    comment character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.cleaner_feedback OWNER TO postgres;

--
-- TOC entry 265 (class 1259 OID 36587)
-- Name: cleaner_feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.cleaner_feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.cleaner_feedback_id_seq OWNER TO postgres;

--
-- TOC entry 6153 (class 0 OID 0)
-- Dependencies: 265
-- Name: cleaner_feedback_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.cleaner_feedback_id_seq OWNED BY public.cleaner_feedback.id;


--
-- TOC entry 221 (class 1259 OID 18771)
-- Name: cleaners; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cleaners (
    id bigint NOT NULL,
    password_hash character varying(255),
    full_name character varying(255),
    phone_number character varying(255),
    email character varying(255) NOT NULL,
    age integer,
    address character varying(255),
    profile_image bytea,
    identity_number character varying(255),
    identity_verified boolean DEFAULT false,
    experience character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status boolean DEFAULT false,
    is_deleted boolean DEFAULT true
);


ALTER TABLE public.cleaners OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 18770)
-- Name: cleaners_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.cleaners_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.cleaners_id_seq OWNER TO postgres;

--
-- TOC entry 6154 (class 0 OID 0)
-- Dependencies: 220
-- Name: cleaners_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.cleaners_id_seq OWNED BY public.cleaners.id;


--
-- TOC entry 247 (class 1259 OID 19110)
-- Name: conversations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.conversations (
    id bigint NOT NULL,
    cleaner_id integer,
    customer_id integer
);


ALTER TABLE public.conversations OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 19109)
-- Name: conversations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.conversations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.conversations_id_seq OWNER TO postgres;

--
-- TOC entry 6155 (class 0 OID 0)
-- Dependencies: 246
-- Name: conversations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.conversations_id_seq OWNED BY public.conversations.id;


--
-- TOC entry 227 (class 1259 OID 18821)
-- Name: customer_addresses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer_addresses (
    id bigint NOT NULL,
    customer_id integer,
    address character varying(255),
    latitude double precision,
    longitude double precision,
    is_default boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) without time zone,
    is_current boolean DEFAULT false NOT NULL,
    geom public.geometry(Point,4326)
);


ALTER TABLE public.customer_addresses OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 18820)
-- Name: customer_addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.customer_addresses_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.customer_addresses_id_seq OWNER TO postgres;

--
-- TOC entry 6156 (class 0 OID 0)
-- Dependencies: 226
-- Name: customer_addresses_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.customer_addresses_id_seq OWNED BY public.customer_addresses.id;


--
-- TOC entry 262 (class 1259 OID 36474)
-- Name: customer_wallet; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer_wallet (
    id bigint NOT NULL,
    customer_id bigint NOT NULL,
    balance double precision DEFAULT 0 NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    txn_ref character varying(255)
);


ALTER TABLE public.customer_wallet OWNER TO postgres;

--
-- TOC entry 261 (class 1259 OID 36473)
-- Name: customer_wallet_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.customer_wallet_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.customer_wallet_id_seq OWNER TO postgres;

--
-- TOC entry 6157 (class 0 OID 0)
-- Dependencies: 261
-- Name: customer_wallet_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.customer_wallet_id_seq OWNED BY public.customer_wallet.id;


--
-- TOC entry 219 (class 1259 OID 18759)
-- Name: customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers (
    id integer NOT NULL,
    password_hash character varying(255),
    full_name character varying(255),
    phone_number character varying(255),
    created_at date DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean DEFAULT true,
    email character varying(255)
);


ALTER TABLE public.customers OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 18758)
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.customers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.customers_id_seq OWNER TO postgres;

--
-- TOC entry 6158 (class 0 OID 0)
-- Dependencies: 218
-- Name: customers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.customers_id_seq OWNED BY public.customers.id;


--
-- TOC entry 243 (class 1259 OID 19031)
-- Name: feedback; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.feedback (
    id bigint NOT NULL,
    job_id bigint,
    rating double precision,
    comment character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT feedback_rating_check CHECK (((rating >= (1)::double precision) AND (rating <= (5)::double precision)))
);


ALTER TABLE public.feedback OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 19030)
-- Name: feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.feedback_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.feedback_id_seq OWNER TO postgres;

--
-- TOC entry 6159 (class 0 OID 0)
-- Dependencies: 242
-- Name: feedback_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.feedback_id_seq OWNED BY public.feedback.id;


--
-- TOC entry 253 (class 1259 OID 19635)
-- Name: job_application; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_application (
    id bigint NOT NULL,
    applied_at timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    cleaner_id bigint NOT NULL,
    job_id bigint NOT NULL
);


ALTER TABLE public.job_application OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 19634)
-- Name: job_application_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job_application ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 18931)
-- Name: job_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_details (
    id bigint NOT NULL,
    job_id bigint,
    room_size integer,
    image_url character varying(255),
    scheduled_time timestamp(6) without time zone
);


ALTER TABLE public.job_details OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 18930)
-- Name: job_details_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.job_details_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.job_details_id_seq OWNER TO postgres;

--
-- TOC entry 6160 (class 0 OID 0)
-- Dependencies: 238
-- Name: job_details_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.job_details_id_seq OWNED BY public.job_details.id;


--
-- TOC entry 255 (class 1259 OID 20068)
-- Name: job_service_detail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_service_detail (
    id bigint NOT NULL,
    job_id bigint NOT NULL,
    service_id bigint NOT NULL,
    service_detail_id bigint NOT NULL
);


ALTER TABLE public.job_service_detail OWNER TO postgres;

--
-- TOC entry 254 (class 1259 OID 20067)
-- Name: job_service_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.job_service_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.job_service_detail_id_seq OWNER TO postgres;

--
-- TOC entry 6161 (class 0 OID 0)
-- Dependencies: 254
-- Name: job_service_detail_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.job_service_detail_id_seq OWNED BY public.job_service_detail.id;


--
-- TOC entry 237 (class 1259 OID 18898)
-- Name: jobs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jobs (
    id bigint NOT NULL,
    customer_id integer,
    service_id bigint,
    service_detail_id bigint,
    status character varying(255) DEFAULT 'Open'::character varying,
    scheduled_time timestamp without time zone,
    total_price double precision,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    customer_address_id bigint,
    cleaner_id integer,
    payment_method character varying(255) DEFAULT 'Cash'::character varying NOT NULL,
    txn_ref character varying(255),
    reminder character varying(255),
    order_code character varying(255) DEFAULT 'DEFAULT_ORDER_CODE'::character varying,
    booking_type character varying(255),
    job_type character varying(255)
);


ALTER TABLE public.jobs OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 18897)
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.jobs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.jobs_id_seq OWNER TO postgres;

--
-- TOC entry 6162 (class 0 OID 0)
-- Dependencies: 236
-- Name: jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.jobs_id_seq OWNED BY public.jobs.id;


--
-- TOC entry 268 (class 1259 OID 36625)
-- Name: messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    message_content character varying(255),
    conversation_id bigint,
    sender_id integer,
    sent_at timestamp(6) without time zone
);


ALTER TABLE public.messages OWNER TO postgres;

--
-- TOC entry 267 (class 1259 OID 36624)
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 19047)
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    user_id integer,
    cleaner_id bigint,
    content character varying(255),
    metadata character varying(255),
    is_read boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 19046)
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.notifications_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.notifications_id_seq OWNER TO postgres;

--
-- TOC entry 6163 (class 0 OID 0)
-- Dependencies: 244
-- Name: notifications_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.notifications_id_seq OWNED BY public.notifications.id;


--
-- TOC entry 274 (class 1259 OID 36664)
-- Name: otp_verification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.otp_verification (
    id bigint NOT NULL,
    phone character varying(255) NOT NULL,
    otp_code character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    verified boolean DEFAULT false
);


ALTER TABLE public.otp_verification OWNER TO postgres;

--
-- TOC entry 276 (class 1259 OID 36682)
-- Name: otp_verification_cleaner; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.otp_verification_cleaner (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone,
    otp_code character varying(255),
    phone character varying(255),
    verified boolean
);


ALTER TABLE public.otp_verification_cleaner OWNER TO postgres;

--
-- TOC entry 275 (class 1259 OID 36681)
-- Name: otp_verification_cleaner_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.otp_verification_cleaner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otp_verification_cleaner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 273 (class 1259 OID 36663)
-- Name: otp_verification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.otp_verification_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.otp_verification_id_seq OWNER TO postgres;

--
-- TOC entry 6164 (class 0 OID 0)
-- Dependencies: 273
-- Name: otp_verification_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.otp_verification_id_seq OWNED BY public.otp_verification.id;


--
-- TOC entry 270 (class 1259 OID 36631)
-- Name: payments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    amount numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    job_id bigint,
    payment_date timestamp(6) without time zone NOT NULL,
    payment_method character varying(255) NOT NULL,
    payment_reference character varying(255),
    payment_status character varying(255) NOT NULL,
    transaction_id character varying(255),
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.payments OWNER TO postgres;

--
-- TOC entry 269 (class 1259 OID 36630)
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 19186)
-- Name: reports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reports (
    id bigint NOT NULL,
    reporter_id integer,
    reported_user_id bigint,
    job_id bigint,
    report_type character varying(255),
    description character varying(255),
    status character varying(255) DEFAULT 'Pending'::character varying,
    created_at date DEFAULT CURRENT_TIMESTAMP,
    updated_at date DEFAULT CURRENT_TIMESTAMP,
    resolved_at date,
    admin_response character varying(255),
    CONSTRAINT reports_report_type_check CHECK (((report_type)::text = ANY (ARRAY[('Fraud'::character varying)::text, ('Poor Service'::character varying)::text, ('Harassment'::character varying)::text, ('Other'::character varying)::text])))
);


ALTER TABLE public.reports OWNER TO postgres;

--
-- TOC entry 280 (class 1259 OID 36739)
-- Name: reports_cleaner; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reports_cleaner (
    id bigint NOT NULL,
    admin_response character varying(255),
    reported_user_id integer,
    created_at date,
    reporter_id integer,
    description character varying(255),
    report_type character varying(255),
    resolved_at date,
    status character varying(255),
    updated_at date,
    job_id bigint,
    CONSTRAINT reports_cleaner_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'REVIEWING'::character varying, 'RESOLVED'::character varying, 'DISMISSED'::character varying, 'CANCEL'::character varying, 'FAIL'::character varying])::text[])))
);


ALTER TABLE public.reports_cleaner OWNER TO postgres;

--
-- TOC entry 279 (class 1259 OID 36738)
-- Name: reports_cleaner_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reports_cleaner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reports_cleaner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 19185)
-- Name: reports_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.reports_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.reports_id_seq OWNER TO postgres;

--
-- TOC entry 6165 (class 0 OID 0)
-- Dependencies: 250
-- Name: reports_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.reports_id_seq OWNED BY public.reports.id;


--
-- TOC entry 223 (class 1259 OID 18789)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    role_name character varying(255),
    description character varying(255)
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 18788)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.roles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.roles_id_seq OWNER TO postgres;

--
-- TOC entry 6166 (class 0 OID 0)
-- Dependencies: 222
-- Name: roles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.roles_id_seq OWNED BY public.roles.id;


--
-- TOC entry 235 (class 1259 OID 18885)
-- Name: service_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service_details (
    id bigint NOT NULL,
    service_id bigint,
    name character varying(255),
    description character varying(255),
    price double precision,
    min_room_size integer,
    max_room_size integer,
    additional_price double precision,
    area_range character varying(255),
    discounts character varying(255),
    peak_time_fee double precision
);


ALTER TABLE public.service_details OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 18884)
-- Name: service_details_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.service_details_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.service_details_id_seq OWNER TO postgres;

--
-- TOC entry 6167 (class 0 OID 0)
-- Dependencies: 234
-- Name: service_details_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.service_details_id_seq OWNED BY public.service_details.id;


--
-- TOC entry 233 (class 1259 OID 18874)
-- Name: services; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services (
    id bigint NOT NULL,
    name character varying(255),
    description character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    base_price double precision,
    is_peak_time_fee boolean,
    max_area integer,
    min_area integer,
    special_discount character varying(255),
    unit character varying(255)
);


ALTER TABLE public.services OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 18873)
-- Name: services_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.services_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.services_id_seq OWNER TO postgres;

--
-- TOC entry 6168 (class 0 OID 0)
-- Dependencies: 232
-- Name: services_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.services_id_seq OWNED BY public.services.id;


--
-- TOC entry 264 (class 1259 OID 36514)
-- Name: transaction_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaction_history (
    transaction_id bigint NOT NULL,
    cleaner_id bigint,
    customer_id bigint,
    amount double precision NOT NULL,
    transaction_type character varying(255) NOT NULL,
    transaction_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    payment_method character varying(255),
    status character varying(255),
    txn_ref character varying(255)
);


ALTER TABLE public.transaction_history OWNER TO postgres;

--
-- TOC entry 263 (class 1259 OID 36513)
-- Name: transaction_history_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.transaction_history_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.transaction_history_transaction_id_seq OWNER TO postgres;

--
-- TOC entry 6169 (class 0 OID 0)
-- Dependencies: 263
-- Name: transaction_history_transaction_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.transaction_history_transaction_id_seq OWNED BY public.transaction_history.transaction_id;


--
-- TOC entry 241 (class 1259 OID 19008)
-- Name: transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    user_id integer,
    cleaner_id bigint,
    amount numeric(38,2),
    transaction_type character varying(255),
    payment_method character varying(255),
    transaction_status character varying(255),
    description text,
    transaction_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    payment_reference character varying(255),
    customer_id integer,
    created_at timestamp(6) without time zone NOT NULL,
    job_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    transaction_id character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT transactions_payment_method_check CHECK (((payment_method)::text = ANY (ARRAY[('Credit Card'::character varying)::text, ('Debit Card'::character varying)::text, ('Bank Transfer'::character varying)::text, ('E-Wallet'::character varying)::text]))),
    CONSTRAINT transactions_transaction_status_check CHECK (((transaction_status)::text = ANY (ARRAY[('Pending'::character varying)::text, ('Completed'::character varying)::text, ('Failed'::character varying)::text, ('Refunded'::character varying)::text]))),
    CONSTRAINT transactions_transaction_type_check CHECK (((transaction_type)::text = ANY (ARRAY[('Credit'::character varying)::text, ('Debit'::character varying)::text])))
);


ALTER TABLE public.transactions OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 19007)
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.transactions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.transactions_id_seq OWNER TO postgres;

--
-- TOC entry 6170 (class 0 OID 0)
-- Dependencies: 240
-- Name: transactions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.transactions_id_seq OWNED BY public.transactions.id;


--
-- TOC entry 231 (class 1259 OID 18854)
-- Name: wallets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wallets (
    id bigint NOT NULL,
    cleaner_id bigint,
    balance double precision DEFAULT 0,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    txn_ref character varying(255)
);


ALTER TABLE public.wallets OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 18853)
-- Name: wallets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.wallets_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.wallets_id_seq OWNER TO postgres;

--
-- TOC entry 6171 (class 0 OID 0)
-- Dependencies: 230
-- Name: wallets_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.wallets_id_seq OWNED BY public.wallets.id;


--
-- TOC entry 272 (class 1259 OID 36641)
-- Name: withdrawal_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.withdrawal_requests (
    id bigint NOT NULL,
    customer_id bigint,
    cleaner_id bigint,
    amount double precision NOT NULL,
    status character varying(255) DEFAULT 'PENDING'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    card_number character varying(255),
    bank_name character varying(255),
    account_holder_name character varying(255),
    reason character varying(255),
    transaction_code character varying(255)
);


ALTER TABLE public.withdrawal_requests OWNER TO postgres;

--
-- TOC entry 271 (class 1259 OID 36640)
-- Name: withdrawal_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.withdrawal_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.withdrawal_requests_id_seq OWNER TO postgres;

--
-- TOC entry 6172 (class 0 OID 0)
-- Dependencies: 271
-- Name: withdrawal_requests_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.withdrawal_requests_id_seq OWNED BY public.withdrawal_requests.id;


--
-- TOC entry 249 (class 1259 OID 19168)
-- Name: work_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.work_history (
    id bigint NOT NULL,
    cleaner_id bigint,
    job_id bigint,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    total_duration integer,
    earnings double precision,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.work_history OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 19167)
-- Name: work_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.work_history_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.work_history_id_seq OWNER TO postgres;

--
-- TOC entry 6173 (class 0 OID 0)
-- Dependencies: 248
-- Name: work_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.work_history_id_seq OWNED BY public.work_history.id;


--
-- TOC entry 5809 (class 2604 OID 19426)
-- Name: administrators id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.administrators ALTER COLUMN id SET DEFAULT nextval('public.administrators_id_seq'::regclass);


--
-- TOC entry 5816 (class 2604 OID 18840)
-- Name: cleaner_addresses id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cleaner_addresses ALTER COLUMN id SET DEFAULT nextval('public.cleaner_addresses_id_seq'::regclass);


--
-- TOC entry 5855 (class 2604 OID 36591)
-- Name: cleaner_feedback id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cleaner_feedback ALTER COLUMN id SET DEFAULT nextval('public.cleaner_feedback_id_seq'::regclass);


--
-- TOC entry 5802 (class 2604 OID 19482)
-- Name: cleaners id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cleaners ALTER COLUMN id SET DEFAULT nextval('public.cleaners_id_seq'::regclass);


--
-- TOC entry 5842 (class 2604 OID 19554)
-- Name: conversations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversations ALTER COLUMN id SET DEFAULT nextval('public.conversations_id_seq'::regclass);


--
-- TOC entry 5812 (class 2604 OID 20017)
-- Name: customer_addresses id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_addresses ALTER COLUMN id SET DEFAULT nextval('public.customer_addresses_id_seq'::regclass);


--
-- TOC entry 5850 (class 2604 OID 36487)
-- Name: customer_wallet id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_wallet ALTER COLUMN id SET DEFAULT nextval('public.customer_wallet_id_seq'::regclass);


--
-- TOC entry 5799 (class 2604 OID 18762)
-- Name: customers id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers ALTER COLUMN id SET DEFAULT nextval('public.customers_id_seq'::regclass);


--
-- TOC entry 5836 (class 2604 OID 19590)
-- Name: feedback id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feedback ALTER COLUMN id SET DEFAULT nextval('public.feedback_id_seq'::regclass);


--
-- TOC entry 5833 (class 2604 OID 19612)
-- Name: job_details id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_details ALTER COLUMN id SET DEFAULT nextval('public.job_details_id_seq'::regclass);


--
-- TOC entry 5849 (class 2604 OID 20071)
-- Name: job_service_detail id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_service_detail ALTER COLUMN id SET DEFAULT nextval('public.job_service_detail_id_seq'::regclass);


--
-- TOC entry 5827 (class 2604 OID 19640)
-- Name: jobs id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs ALTER COLUMN id SET DEFAULT nextval('public.jobs_id_seq'::regclass);


--
-- TOC entry 5839 (class 2604 OID 19792)
-- Name: notifications id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications ALTER COLUMN id SET DEFAULT nextval('public.notifications_id_seq'::regclass);


--
-- TOC entry 5862 (class 2604 OID 36672)
-- Name: otp_verification id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.otp_verification ALTER COLUMN id SET DEFAULT nextval('public.otp_verification_id_seq'::regclass);


--
-- TOC entry 5845 (class 2604 OID 19824)
-- Name: reports id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports ALTER COLUMN id SET DEFAULT nextval('public.reports_id_seq'::regclass);


--
-- TOC entry 5808 (class 2604 OID 19870)
-- Name: roles id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles ALTER COLUMN id SET DEFAULT nextval('public.roles_id_seq'::regclass);


--
-- TOC entry 5826 (class 2604 OID 19248)
-- Name: service_details id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_details ALTER COLUMN id SET DEFAULT nextval('public.service_details_id_seq'::regclass);


--
-- TOC entry 5823 (class 2604 OID 19274)
-- Name: services id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services ALTER COLUMN id SET DEFAULT nextval('public.services_id_seq'::regclass);


--
-- TOC entry 5853 (class 2604 OID 36517)
-- Name: transaction_history transaction_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_history ALTER COLUMN transaction_id SET DEFAULT nextval('public.transaction_history_transaction_id_seq'::regclass);


--
-- TOC entry 5834 (class 2604 OID 19895)
-- Name: transactions id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions ALTER COLUMN id SET DEFAULT nextval('public.transactions_id_seq'::regclass);


--
-- TOC entry 5820 (class 2604 OID 19944)
-- Name: wallets id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallets ALTER COLUMN id SET DEFAULT nextval('public.wallets_id_seq'::regclass);


--
-- TOC entry 5858 (class 2604 OID 36644)
-- Name: withdrawal_requests id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.withdrawal_requests ALTER COLUMN id SET DEFAULT nextval('public.withdrawal_requests_id_seq'::regclass);


--
-- TOC entry 5843 (class 2604 OID 19965)
-- Name: work_history id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.work_history ALTER COLUMN id SET DEFAULT nextval('public.work_history_id_seq'::regclass);


--
-- TOC entry 5948 (class 2606 OID 36727)
-- Name: admin_transaction_history admin_transaction_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_transaction_history
    ADD CONSTRAINT admin_transaction_history_pkey PRIMARY KEY (id);


--
-- TOC entry 5890 (class 2606 OID 18812)
-- Name: administrators administrators_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.administrators
    ADD CONSTRAINT administrators_email_key UNIQUE (email);


--
-- TOC entry 5892 (class 2606 OID 18814)
-- Name: administrators administrators_fullname_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.administrators
    ADD CONSTRAINT administrators_fullname_key UNIQUE (fullname);


--
-- TOC entry 5894 (class 2606 OID 19428)
-- Name: administrators administrators_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.administrators
    ADD CONSTRAINT administrators_pkey PRIMARY KEY (id);


--
-- TOC entry 5898 (class 2606 OID 18847)
-- Name: cleaner_addresses cleaner_addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cleaner_addresses
    ADD CONSTRAINT cleaner_addresses_pkey PRIMARY KEY (id);


--
-- TOC entry 5934 (class 2606 OID 36599)
-- Name: cleaner_feedback cleaner_feedback_job_id_cleaner_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cleaner_feedback
    ADD CONSTRAINT cleaner_feedback_job_id_cleaner_id_key UNIQUE (job_id, cleaner_id);


--
-- TOC entry 5936 (class 2606 OID 36597)
-- Name: cleaner_feedback cleaner_feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cleaner_feedback
    ADD CONSTRAINT cleaner_feedback_pkey PRIMARY KEY (id);


--
-- TOC entry 5878 (class 2606 OID 18785)
-- Name: cleaners cleaners_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cleaners
    ADD CONSTRAINT cleaners_email_key UNIQUE (email);


--
-- TOC entry 5880 (class 2606 OID 19234)
-- Name: cleaners cleaners_identity_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cleaners
    ADD CONSTRAINT cleaners_identity_number_key UNIQUE (identity_number);


--
-- TOC entry 5882 (class 2606 OID 19236)
-- Name: cleaners cleaners_phone_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cleaners
    ADD CONSTRAINT cleaners_phone_number_key UNIQUE (phone_number);


--
-- TOC entry 5884 (class 2606 OID 19484)
-- Name: cleaners cleaners_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cleaners
    ADD CONSTRAINT cleaners_pkey PRIMARY KEY (id);


--
-- TOC entry 5918 (class 2606 OID 19556)
-- Name: conversations conversations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_pkey PRIMARY KEY (id);


--
-- TOC entry 5896 (class 2606 OID 20019)
-- Name: customer_addresses customer_addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_addresses
    ADD CONSTRAINT customer_addresses_pkey PRIMARY KEY (id);


--
-- TOC entry 5930 (class 2606 OID 36489)
-- Name: customer_wallet customer_wallet_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_wallet
    ADD CONSTRAINT customer_wallet_pkey PRIMARY KEY (id);


--
-- TOC entry 5874 (class 2606 OID 19238)
-- Name: customers customers_phone_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_phone_number_key UNIQUE (phone_number);


--
-- TOC entry 5876 (class 2606 OID 18767)
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- TOC entry 5914 (class 2606 OID 19592)
-- Name: feedback feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_pkey PRIMARY KEY (id);


--
-- TOC entry 5924 (class 2606 OID 19639)
-- Name: job_application job_application_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_application
    ADD CONSTRAINT job_application_pkey PRIMARY KEY (id);


--
-- TOC entry 5908 (class 2606 OID 19614)
-- Name: job_details job_details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_details
    ADD CONSTRAINT job_details_pkey PRIMARY KEY (id);


--
-- TOC entry 5926 (class 2606 OID 20073)
-- Name: job_service_detail job_service_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_service_detail
    ADD CONSTRAINT job_service_detail_pkey PRIMARY KEY (id);


--
-- TOC entry 5906 (class 2606 OID 19642)
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- TOC entry 5938 (class 2606 OID 36629)
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- TOC entry 5916 (class 2606 OID 19794)
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- TOC entry 5946 (class 2606 OID 36688)
-- Name: otp_verification_cleaner otp_verification_cleaner_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.otp_verification_cleaner
    ADD CONSTRAINT otp_verification_cleaner_pkey PRIMARY KEY (id);


--
-- TOC entry 5944 (class 2606 OID 36674)
-- Name: otp_verification otp_verification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.otp_verification
    ADD CONSTRAINT otp_verification_pkey PRIMARY KEY (id);


--
-- TOC entry 5940 (class 2606 OID 36637)
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- TOC entry 5950 (class 2606 OID 36746)
-- Name: reports_cleaner reports_cleaner_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports_cleaner
    ADD CONSTRAINT reports_cleaner_pkey PRIMARY KEY (id);


--
-- TOC entry 5922 (class 2606 OID 19826)
-- Name: reports reports_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_pkey PRIMARY KEY (id);


--
-- TOC entry 5886 (class 2606 OID 19872)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 5888 (class 2606 OID 19891)
-- Name: roles roles_role_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_role_name_key UNIQUE (role_name);


--
-- TOC entry 5904 (class 2606 OID 19250)
-- Name: service_details service_details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_details
    ADD CONSTRAINT service_details_pkey PRIMARY KEY (id);


--
-- TOC entry 5902 (class 2606 OID 19276)
-- Name: services services_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT services_pkey PRIMARY KEY (id);


--
-- TOC entry 5932 (class 2606 OID 36520)
-- Name: transaction_history transaction_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_history
    ADD CONSTRAINT transaction_history_pkey PRIMARY KEY (transaction_id);


--
-- TOC entry 5910 (class 2606 OID 19897)
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- TOC entry 5952 (class 2606 OID 36748)
-- Name: reports_cleaner uk62en4g4h6tvnoiy1kfr1mhv4e; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports_cleaner
    ADD CONSTRAINT uk62en4g4h6tvnoiy1kfr1mhv4e UNIQUE (job_id);


--
-- TOC entry 5912 (class 2606 OID 20126)
-- Name: transactions uk6plyfbm3wy6ds7hongoml5xbk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT uk6plyfbm3wy6ds7hongoml5xbk UNIQUE (transaction_id);


--
-- TOC entry 5900 (class 2606 OID 19946)
-- Name: wallets wallets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT wallets_pkey PRIMARY KEY (id);


--
-- TOC entry 5942 (class 2606 OID 36649)
-- Name: withdrawal_requests withdrawal_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.withdrawal_requests
    ADD CONSTRAINT withdrawal_requests_pkey PRIMARY KEY (id);


--
-- TOC entry 5920 (class 2606 OID 19967)
-- Name: work_history work_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.work_history
    ADD CONSTRAINT work_history_pkey PRIMARY KEY (id);


--
-- TOC entry 5994 (class 2620 OID 36623)
-- Name: cleaner_feedback update_cleaner_feedback_updated_at_trigger; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_cleaner_feedback_updated_at_trigger BEFORE UPDATE ON public.cleaner_feedback FOR EACH ROW EXECUTE FUNCTION public.update_cleaner_feedback_updated_at();


--
-- TOC entry 5992 (class 2620 OID 36620)
-- Name: feedback update_cleaner_feedback_updated_at_trigger; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_cleaner_feedback_updated_at_trigger BEFORE UPDATE ON public.feedback FOR EACH ROW EXECUTE FUNCTION public.update_cleaner_feedback_updated_at();


--
-- TOC entry 5993 (class 2620 OID 36537)
-- Name: feedback update_feedback_updated_at_trigger; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_feedback_updated_at_trigger BEFORE UPDATE ON public.feedback FOR EACH ROW EXECUTE FUNCTION public.update_feedback_updated_at();


--
-- TOC entry 5953 (class 2606 OID 19873)
-- Name: administrators administrators_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.administrators
    ADD CONSTRAINT administrators_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- TOC entry 5955 (class 2606 OID 19485)
-- Name: cleaner_addresses cleaner_addresses_cleaner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cleaner_addresses
    ADD CONSTRAINT cleaner_addresses_cleaner_id_fkey FOREIGN KEY (cleaner_id) REFERENCES public.cleaners(id);


--
-- TOC entry 5985 (class 2606 OID 36605)
-- Name: cleaner_feedback cleaner_feedback_cleaner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cleaner_feedback
    ADD CONSTRAINT cleaner_feedback_cleaner_id_fkey FOREIGN KEY (cleaner_id) REFERENCES public.cleaners(id);


--
-- TOC entry 5986 (class 2606 OID 36600)
-- Name: cleaner_feedback cleaner_feedback_job_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cleaner_feedback
    ADD CONSTRAINT cleaner_feedback_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id);


--
-- TOC entry 5954 (class 2606 OID 18831)
-- Name: customer_addresses customer_addresses_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_addresses
    ADD CONSTRAINT customer_addresses_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- TOC entry 5982 (class 2606 OID 36482)
-- Name: customer_wallet customer_wallet_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_wallet
    ADD CONSTRAINT customer_wallet_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;


--
-- TOC entry 5967 (class 2606 OID 19673)
-- Name: feedback feedback_job_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id);


--
-- TOC entry 5977 (class 2606 OID 19999)
-- Name: job_application fk10hrhnupwe0fiknw4bt4u49fp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_application
    ADD CONSTRAINT fk10hrhnupwe0fiknw4bt4u49fp FOREIGN KEY (job_id) REFERENCES public.jobs(id);


--
-- TOC entry 5958 (class 2606 OID 20060)
-- Name: jobs fk2en9mx5vlffma3axkajqfwfog; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fk2en9mx5vlffma3axkajqfwfog FOREIGN KEY (cleaner_id) REFERENCES public.cleaners(id);


--
-- TOC entry 5978 (class 2606 OID 19994)
-- Name: job_application fk3lr9175bok4ndpjwkjhb0og4p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_application
    ADD CONSTRAINT fk3lr9175bok4ndpjwkjhb0og4p FOREIGN KEY (cleaner_id) REFERENCES public.cleaners(id);


--
-- TOC entry 5991 (class 2606 OID 36749)
-- Name: reports_cleaner fk7dpced3lx6c4fmkgxlhte23ok; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports_cleaner
    ADD CONSTRAINT fk7dpced3lx6c4fmkgxlhte23ok FOREIGN KEY (job_id) REFERENCES public.jobs(id);


--
-- TOC entry 5970 (class 2606 OID 29391)
-- Name: conversations fk7lux8582tbwm29irjwncsboau; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fk7lux8582tbwm29irjwncsboau FOREIGN KEY (cleaner_id) REFERENCES public.cleaners(id);


--
-- TOC entry 5989 (class 2606 OID 36728)
-- Name: admin_transaction_history fk9nlgq3ab2epx6t5fsq0xg7xcx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_transaction_history
    ADD CONSTRAINT fk9nlgq3ab2epx6t5fsq0xg7xcx FOREIGN KEY (cleaner_id) REFERENCES public.cleaners(id);


--
-- TOC entry 5959 (class 2606 OID 20020)
-- Name: jobs fk_customer_address; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fk_customer_address FOREIGN KEY (customer_address_id) REFERENCES public.customer_addresses(id);


--
-- TOC entry 5971 (class 2606 OID 29396)
-- Name: conversations fkhrqycoqjka1jcpl4k2namguhb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fkhrqycoqjka1jcpl4k2namguhb FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- TOC entry 5964 (class 2606 OID 20004)
-- Name: transactions fkpnnreq9lpejqyjfct60v7n7x1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkpnnreq9lpejqyjfct60v7n7x1 FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- TOC entry 5990 (class 2606 OID 36733)
-- Name: admin_transaction_history fkr502302310vufaps7icl194xm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_transaction_history
    ADD CONSTRAINT fkr502302310vufaps7icl194xm FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- TOC entry 5963 (class 2606 OID 19678)
-- Name: job_details job_details_job_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_details
    ADD CONSTRAINT job_details_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id);


--
-- TOC entry 5979 (class 2606 OID 20074)
-- Name: job_service_detail job_service_detail_job_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_service_detail
    ADD CONSTRAINT job_service_detail_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE;


--
-- TOC entry 5980 (class 2606 OID 20084)
-- Name: job_service_detail job_service_detail_service_detail_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_service_detail
    ADD CONSTRAINT job_service_detail_service_detail_id_fkey FOREIGN KEY (service_detail_id) REFERENCES public.service_details(id) ON DELETE CASCADE;


--
-- TOC entry 5981 (class 2606 OID 20079)
-- Name: job_service_detail job_service_detail_service_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_service_detail
    ADD CONSTRAINT job_service_detail_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id) ON DELETE CASCADE;


--
-- TOC entry 5960 (class 2606 OID 18910)
-- Name: jobs jobs_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- TOC entry 5961 (class 2606 OID 19755)
-- Name: jobs jobs_service_detail_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_service_detail_id_fkey FOREIGN KEY (service_detail_id) REFERENCES public.service_details(id);


--
-- TOC entry 5962 (class 2606 OID 19744)
-- Name: jobs jobs_service_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id);


--
-- TOC entry 5968 (class 2606 OID 19813)
-- Name: notifications notifications_cleaner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_cleaner_id_fkey FOREIGN KEY (cleaner_id) REFERENCES public.cleaners(id);


--
-- TOC entry 5969 (class 2606 OID 19057)
-- Name: notifications notifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.customers(id);


--
-- TOC entry 5974 (class 2606 OID 19848)
-- Name: reports reports_job_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id);


--
-- TOC entry 5975 (class 2606 OID 19859)
-- Name: reports reports_reported_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_reported_user_id_fkey FOREIGN KEY (reported_user_id) REFERENCES public.cleaners(id);


--
-- TOC entry 5976 (class 2606 OID 19199)
-- Name: reports reports_reporter_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES public.customers(id);


--
-- TOC entry 5957 (class 2606 OID 19282)
-- Name: service_details service_details_service_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_details
    ADD CONSTRAINT service_details_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id);


--
-- TOC entry 5983 (class 2606 OID 36521)
-- Name: transaction_history transaction_history_cleaner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_history
    ADD CONSTRAINT transaction_history_cleaner_id_fkey FOREIGN KEY (cleaner_id) REFERENCES public.cleaners(id) ON DELETE CASCADE;


--
-- TOC entry 5984 (class 2606 OID 36526)
-- Name: transaction_history transaction_history_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_history
    ADD CONSTRAINT transaction_history_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;


--
-- TOC entry 5965 (class 2606 OID 19913)
-- Name: transactions transactions_cleaner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_cleaner_id_fkey FOREIGN KEY (cleaner_id) REFERENCES public.cleaners(id);


--
-- TOC entry 5966 (class 2606 OID 19020)
-- Name: transactions transactions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.customers(id);


--
-- TOC entry 5956 (class 2606 OID 19956)
-- Name: wallets wallets_cleaner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT wallets_cleaner_id_fkey FOREIGN KEY (cleaner_id) REFERENCES public.cleaners(id);


--
-- TOC entry 5987 (class 2606 OID 36655)
-- Name: withdrawal_requests withdrawal_requests_cleaner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.withdrawal_requests
    ADD CONSTRAINT withdrawal_requests_cleaner_id_fkey FOREIGN KEY (cleaner_id) REFERENCES public.cleaners(id) ON DELETE CASCADE;


--
-- TOC entry 5988 (class 2606 OID 36650)
-- Name: withdrawal_requests withdrawal_requests_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.withdrawal_requests
    ADD CONSTRAINT withdrawal_requests_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;


--
-- TOC entry 5972 (class 2606 OID 19976)
-- Name: work_history work_history_cleaner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.work_history
    ADD CONSTRAINT work_history_cleaner_id_fkey FOREIGN KEY (cleaner_id) REFERENCES public.cleaners(id);


--
-- TOC entry 5973 (class 2606 OID 19985)
-- Name: work_history work_history_job_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.work_history
    ADD CONSTRAINT work_history_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id);


-- Completed on 2025-04-29 15:24:02

--
-- PostgreSQL database dump complete
--

