name: Deploy Frontend to Firebase

on: 
   push:
    branches:
      - main 
    paths:
      - "FE/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
         node-version: 18

     - name: Install dependencies
       run: |
        cd FE
        npm install 
     
     - name: Build project
       run: |
        cd FE
        npm run build

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@v12
      with: 
        args: deploy --only hosting
      env:
         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      working-directory: FE 
